version: '3.9'
services:
  db:
    image: mongo
    # hostname: test-mongo
    # container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=synapsis_challenge
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # volumes:
    #   - '.mongodata:/data/db'
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://username:password@db:27017/
    depends_on:
      - db
  app:
    build: .
    ports:
      - '11000:11000'
    depends_on:
      - db
